// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_data.proto

#include "world_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_world_5fdata_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_world_5fdata_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Coord;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_world_5fdata_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_WheelsVelocity;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_world_5fdata_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Position;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_world_5fdata_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_RobotData;
}  // namespace protobuf_world_5fdata_2eproto
namespace protocol {
class CoordDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Coord>
      _instance;
} _Coord_default_instance_;
class PositionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Position>
      _instance;
} _Position_default_instance_;
class WheelsVelocityDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WheelsVelocity>
      _instance;
} _WheelsVelocity_default_instance_;
class RobotDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RobotData>
      _instance;
} _RobotData_default_instance_;
class WorldDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WorldData>
      _instance;
} _WorldData_default_instance_;
}  // namespace protocol
namespace protobuf_world_5fdata_2eproto {
static void InitDefaultsCoord() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_Coord_default_instance_;
    new (ptr) ::protocol::Coord();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::Coord::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Coord =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCoord}, {}};

static void InitDefaultsPosition() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_Position_default_instance_;
    new (ptr) ::protocol::Position();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::Position::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Position =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPosition}, {
      &protobuf_world_5fdata_2eproto::scc_info_Coord.base,}};

static void InitDefaultsWheelsVelocity() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_WheelsVelocity_default_instance_;
    new (ptr) ::protocol::WheelsVelocity();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::WheelsVelocity::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WheelsVelocity =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWheelsVelocity}, {}};

static void InitDefaultsRobotData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_RobotData_default_instance_;
    new (ptr) ::protocol::RobotData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::RobotData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_RobotData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsRobotData}, {
      &protobuf_world_5fdata_2eproto::scc_info_Position.base,
      &protobuf_world_5fdata_2eproto::scc_info_WheelsVelocity.base,}};

static void InitDefaultsWorldData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protocol::_WorldData_default_instance_;
    new (ptr) ::protocol::WorldData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::WorldData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_WorldData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsWorldData}, {
      &protobuf_world_5fdata_2eproto::scc_info_RobotData.base,
      &protobuf_world_5fdata_2eproto::scc_info_Coord.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Coord.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Position.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WheelsVelocity.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RobotData.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WorldData.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Coord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Coord, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Coord, y_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Position, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Position, coord_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::Position, theta_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WheelsVelocity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WheelsVelocity, leftwheelvelocity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WheelsVelocity, rightwheelvelocity_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::RobotData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::RobotData, position_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::RobotData, wheelsvelocity_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WorldData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WorldData, robotdata_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WorldData, obstaclecoords_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::WorldData, ballcoord_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protocol::Coord)},
  { 7, -1, sizeof(::protocol::Position)},
  { 14, -1, sizeof(::protocol::WheelsVelocity)},
  { 21, -1, sizeof(::protocol::RobotData)},
  { 28, -1, sizeof(::protocol::WorldData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_Coord_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_Position_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_WheelsVelocity_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_RobotData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_WorldData_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "world_data.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020world_data.proto\022\010protocol\"\035\n\005Coord\022\t\n"
      "\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"9\n\010Position\022\036\n\005coord"
      "\030\001 \001(\0132\017.protocol.Coord\022\r\n\005theta\030\002 \001(\001\"G"
      "\n\016WheelsVelocity\022\031\n\021leftWheelVelocity\030\001 "
      "\001(\001\022\032\n\022rightWheelVelocity\030\002 \001(\001\"c\n\tRobot"
      "Data\022$\n\010position\030\001 \001(\0132\022.protocol.Positi"
      "on\0220\n\016wheelsVelocity\030\002 \001(\0132\030.protocol.Wh"
      "eelsVelocity\"\200\001\n\tWorldData\022&\n\trobotData\030"
      "\001 \001(\0132\023.protocol.RobotData\022\'\n\016obstacleCo"
      "ords\030\002 \003(\0132\017.protocol.Coord\022\"\n\tballCoord"
      "\030\003 \001(\0132\017.protocol.Coordb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 431);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "world_data.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_world_5fdata_2eproto
namespace protocol {

// ===================================================================

void Coord::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Coord::kXFieldNumber;
const int Coord::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Coord::Coord()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_world_5fdata_2eproto::scc_info_Coord.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.Coord)
}
Coord::Coord(const Coord& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:protocol.Coord)
}

void Coord::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
}

Coord::~Coord() {
  // @@protoc_insertion_point(destructor:protocol.Coord)
  SharedDtor();
}

void Coord::SharedDtor() {
}

void Coord::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Coord::descriptor() {
  ::protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Coord& Coord::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_world_5fdata_2eproto::scc_info_Coord.base);
  return *internal_default_instance();
}


void Coord::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Coord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
  _internal_metadata_.Clear();
}

bool Coord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.Coord)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.Coord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.Coord)
  return false;
#undef DO_
}

void Coord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.Coord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.Coord)
}

::google::protobuf::uint8* Coord::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Coord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.Coord)
  return target;
}

size_t Coord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.Coord)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Coord::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.Coord)
  GOOGLE_DCHECK_NE(&from, this);
  const Coord* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Coord>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.Coord)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.Coord)
    MergeFrom(*source);
  }
}

void Coord::MergeFrom(const Coord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.Coord)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void Coord::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.Coord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Coord::CopyFrom(const Coord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Coord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Coord::IsInitialized() const {
  return true;
}

void Coord::Swap(Coord* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Coord::InternalSwap(Coord* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Coord::GetMetadata() const {
  protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Position::InitAsDefaultInstance() {
  ::protocol::_Position_default_instance_._instance.get_mutable()->coord_ = const_cast< ::protocol::Coord*>(
      ::protocol::Coord::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Position::kCoordFieldNumber;
const int Position::kThetaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Position::Position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_world_5fdata_2eproto::scc_info_Position.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.Position)
}
Position::Position(const Position& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_coord()) {
    coord_ = new ::protocol::Coord(*from.coord_);
  } else {
    coord_ = NULL;
  }
  theta_ = from.theta_;
  // @@protoc_insertion_point(copy_constructor:protocol.Position)
}

void Position::SharedCtor() {
  ::memset(&coord_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&theta_) -
      reinterpret_cast<char*>(&coord_)) + sizeof(theta_));
}

Position::~Position() {
  // @@protoc_insertion_point(destructor:protocol.Position)
  SharedDtor();
}

void Position::SharedDtor() {
  if (this != internal_default_instance()) delete coord_;
}

void Position::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Position::descriptor() {
  ::protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Position& Position::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_world_5fdata_2eproto::scc_info_Position.base);
  return *internal_default_instance();
}


void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && coord_ != NULL) {
    delete coord_;
  }
  coord_ = NULL;
  theta_ = 0;
  _internal_metadata_.Clear();
}

bool Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.Position)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .protocol.Coord coord = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_coord()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double theta = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &theta_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.Position)
  return false;
#undef DO_
}

void Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.Coord coord = 1;
  if (this->has_coord()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_coord(), output);
  }

  // double theta = 2;
  if (this->theta() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->theta(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.Position)
}

::google::protobuf::uint8* Position::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.Coord coord = 1;
  if (this->has_coord()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_coord(), deterministic, target);
  }

  // double theta = 2;
  if (this->theta() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->theta(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.Position)
  return target;
}

size_t Position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.Position)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .protocol.Coord coord = 1;
  if (this->has_coord()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *coord_);
  }

  // double theta = 2;
  if (this->theta() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Position::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.Position)
  GOOGLE_DCHECK_NE(&from, this);
  const Position* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Position>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.Position)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.Position)
    MergeFrom(*source);
  }
}

void Position::MergeFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.Position)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_coord()) {
    mutable_coord()->::protocol::Coord::MergeFrom(from.coord());
  }
  if (from.theta() != 0) {
    set_theta(from.theta());
  }
}

void Position::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Position::CopyFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Position::IsInitialized() const {
  return true;
}

void Position::Swap(Position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Position::InternalSwap(Position* other) {
  using std::swap;
  swap(coord_, other->coord_);
  swap(theta_, other->theta_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Position::GetMetadata() const {
  protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WheelsVelocity::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WheelsVelocity::kLeftWheelVelocityFieldNumber;
const int WheelsVelocity::kRightWheelVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WheelsVelocity::WheelsVelocity()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_world_5fdata_2eproto::scc_info_WheelsVelocity.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.WheelsVelocity)
}
WheelsVelocity::WheelsVelocity(const WheelsVelocity& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&leftwheelvelocity_, &from.leftwheelvelocity_,
    static_cast<size_t>(reinterpret_cast<char*>(&rightwheelvelocity_) -
    reinterpret_cast<char*>(&leftwheelvelocity_)) + sizeof(rightwheelvelocity_));
  // @@protoc_insertion_point(copy_constructor:protocol.WheelsVelocity)
}

void WheelsVelocity::SharedCtor() {
  ::memset(&leftwheelvelocity_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rightwheelvelocity_) -
      reinterpret_cast<char*>(&leftwheelvelocity_)) + sizeof(rightwheelvelocity_));
}

WheelsVelocity::~WheelsVelocity() {
  // @@protoc_insertion_point(destructor:protocol.WheelsVelocity)
  SharedDtor();
}

void WheelsVelocity::SharedDtor() {
}

void WheelsVelocity::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* WheelsVelocity::descriptor() {
  ::protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WheelsVelocity& WheelsVelocity::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_world_5fdata_2eproto::scc_info_WheelsVelocity.base);
  return *internal_default_instance();
}


void WheelsVelocity::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.WheelsVelocity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&leftwheelvelocity_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rightwheelvelocity_) -
      reinterpret_cast<char*>(&leftwheelvelocity_)) + sizeof(rightwheelvelocity_));
  _internal_metadata_.Clear();
}

bool WheelsVelocity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.WheelsVelocity)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double leftWheelVelocity = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &leftwheelvelocity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double rightWheelVelocity = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rightwheelvelocity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.WheelsVelocity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.WheelsVelocity)
  return false;
#undef DO_
}

void WheelsVelocity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.WheelsVelocity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->leftwheelvelocity(), output);
  }

  // double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->rightwheelvelocity(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.WheelsVelocity)
}

::google::protobuf::uint8* WheelsVelocity::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.WheelsVelocity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->leftwheelvelocity(), target);
  }

  // double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->rightwheelvelocity(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.WheelsVelocity)
  return target;
}

size_t WheelsVelocity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.WheelsVelocity)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    total_size += 1 + 8;
  }

  // double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WheelsVelocity::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.WheelsVelocity)
  GOOGLE_DCHECK_NE(&from, this);
  const WheelsVelocity* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WheelsVelocity>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.WheelsVelocity)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.WheelsVelocity)
    MergeFrom(*source);
  }
}

void WheelsVelocity::MergeFrom(const WheelsVelocity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.WheelsVelocity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.leftwheelvelocity() != 0) {
    set_leftwheelvelocity(from.leftwheelvelocity());
  }
  if (from.rightwheelvelocity() != 0) {
    set_rightwheelvelocity(from.rightwheelvelocity());
  }
}

void WheelsVelocity::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.WheelsVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WheelsVelocity::CopyFrom(const WheelsVelocity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.WheelsVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WheelsVelocity::IsInitialized() const {
  return true;
}

void WheelsVelocity::Swap(WheelsVelocity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WheelsVelocity::InternalSwap(WheelsVelocity* other) {
  using std::swap;
  swap(leftwheelvelocity_, other->leftwheelvelocity_);
  swap(rightwheelvelocity_, other->rightwheelvelocity_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WheelsVelocity::GetMetadata() const {
  protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RobotData::InitAsDefaultInstance() {
  ::protocol::_RobotData_default_instance_._instance.get_mutable()->position_ = const_cast< ::protocol::Position*>(
      ::protocol::Position::internal_default_instance());
  ::protocol::_RobotData_default_instance_._instance.get_mutable()->wheelsvelocity_ = const_cast< ::protocol::WheelsVelocity*>(
      ::protocol::WheelsVelocity::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RobotData::kPositionFieldNumber;
const int RobotData::kWheelsVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RobotData::RobotData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_world_5fdata_2eproto::scc_info_RobotData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.RobotData)
}
RobotData::RobotData(const RobotData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_position()) {
    position_ = new ::protocol::Position(*from.position_);
  } else {
    position_ = NULL;
  }
  if (from.has_wheelsvelocity()) {
    wheelsvelocity_ = new ::protocol::WheelsVelocity(*from.wheelsvelocity_);
  } else {
    wheelsvelocity_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:protocol.RobotData)
}

void RobotData::SharedCtor() {
  ::memset(&position_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&wheelsvelocity_) -
      reinterpret_cast<char*>(&position_)) + sizeof(wheelsvelocity_));
}

RobotData::~RobotData() {
  // @@protoc_insertion_point(destructor:protocol.RobotData)
  SharedDtor();
}

void RobotData::SharedDtor() {
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete wheelsvelocity_;
}

void RobotData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RobotData::descriptor() {
  ::protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RobotData& RobotData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_world_5fdata_2eproto::scc_info_RobotData.base);
  return *internal_default_instance();
}


void RobotData::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.RobotData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
  if (GetArenaNoVirtual() == NULL && wheelsvelocity_ != NULL) {
    delete wheelsvelocity_;
  }
  wheelsvelocity_ = NULL;
  _internal_metadata_.Clear();
}

bool RobotData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.RobotData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .protocol.Position position = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .protocol.WheelsVelocity wheelsVelocity = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_wheelsvelocity()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.RobotData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.RobotData)
  return false;
#undef DO_
}

void RobotData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.RobotData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.Position position = 1;
  if (this->has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_position(), output);
  }

  // .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_wheelsvelocity(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.RobotData)
}

::google::protobuf::uint8* RobotData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.RobotData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.Position position = 1;
  if (this->has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_position(), deterministic, target);
  }

  // .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_wheelsvelocity(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.RobotData)
  return target;
}

size_t RobotData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.RobotData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .protocol.Position position = 1;
  if (this->has_position()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *position_);
  }

  // .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *wheelsvelocity_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RobotData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.RobotData)
  GOOGLE_DCHECK_NE(&from, this);
  const RobotData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RobotData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.RobotData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.RobotData)
    MergeFrom(*source);
  }
}

void RobotData::MergeFrom(const RobotData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.RobotData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_position()) {
    mutable_position()->::protocol::Position::MergeFrom(from.position());
  }
  if (from.has_wheelsvelocity()) {
    mutable_wheelsvelocity()->::protocol::WheelsVelocity::MergeFrom(from.wheelsvelocity());
  }
}

void RobotData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.RobotData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotData::CopyFrom(const RobotData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.RobotData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotData::IsInitialized() const {
  return true;
}

void RobotData::Swap(RobotData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RobotData::InternalSwap(RobotData* other) {
  using std::swap;
  swap(position_, other->position_);
  swap(wheelsvelocity_, other->wheelsvelocity_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RobotData::GetMetadata() const {
  protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WorldData::InitAsDefaultInstance() {
  ::protocol::_WorldData_default_instance_._instance.get_mutable()->robotdata_ = const_cast< ::protocol::RobotData*>(
      ::protocol::RobotData::internal_default_instance());
  ::protocol::_WorldData_default_instance_._instance.get_mutable()->ballcoord_ = const_cast< ::protocol::Coord*>(
      ::protocol::Coord::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WorldData::kRobotDataFieldNumber;
const int WorldData::kObstacleCoordsFieldNumber;
const int WorldData::kBallCoordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WorldData::WorldData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_world_5fdata_2eproto::scc_info_WorldData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.WorldData)
}
WorldData::WorldData(const WorldData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      obstaclecoords_(from.obstaclecoords_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_robotdata()) {
    robotdata_ = new ::protocol::RobotData(*from.robotdata_);
  } else {
    robotdata_ = NULL;
  }
  if (from.has_ballcoord()) {
    ballcoord_ = new ::protocol::Coord(*from.ballcoord_);
  } else {
    ballcoord_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:protocol.WorldData)
}

void WorldData::SharedCtor() {
  ::memset(&robotdata_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ballcoord_) -
      reinterpret_cast<char*>(&robotdata_)) + sizeof(ballcoord_));
}

WorldData::~WorldData() {
  // @@protoc_insertion_point(destructor:protocol.WorldData)
  SharedDtor();
}

void WorldData::SharedDtor() {
  if (this != internal_default_instance()) delete robotdata_;
  if (this != internal_default_instance()) delete ballcoord_;
}

void WorldData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* WorldData::descriptor() {
  ::protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WorldData& WorldData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_world_5fdata_2eproto::scc_info_WorldData.base);
  return *internal_default_instance();
}


void WorldData::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.WorldData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  obstaclecoords_.Clear();
  if (GetArenaNoVirtual() == NULL && robotdata_ != NULL) {
    delete robotdata_;
  }
  robotdata_ = NULL;
  if (GetArenaNoVirtual() == NULL && ballcoord_ != NULL) {
    delete ballcoord_;
  }
  ballcoord_ = NULL;
  _internal_metadata_.Clear();
}

bool WorldData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.WorldData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .protocol.RobotData robotData = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_robotdata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .protocol.Coord obstacleCoords = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_obstaclecoords()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .protocol.Coord ballCoord = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_ballcoord()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.WorldData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.WorldData)
  return false;
#undef DO_
}

void WorldData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.WorldData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_robotdata(), output);
  }

  // repeated .protocol.Coord obstacleCoords = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->obstaclecoords_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->obstaclecoords(static_cast<int>(i)),
      output);
  }

  // .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_ballcoord(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.WorldData)
}

::google::protobuf::uint8* WorldData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.WorldData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_robotdata(), deterministic, target);
  }

  // repeated .protocol.Coord obstacleCoords = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->obstaclecoords_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->obstaclecoords(static_cast<int>(i)), deterministic, target);
  }

  // .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_ballcoord(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.WorldData)
  return target;
}

size_t WorldData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.WorldData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protocol.Coord obstacleCoords = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->obstaclecoords_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->obstaclecoords(static_cast<int>(i)));
    }
  }

  // .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *robotdata_);
  }

  // .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *ballcoord_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WorldData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.WorldData)
  GOOGLE_DCHECK_NE(&from, this);
  const WorldData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WorldData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.WorldData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.WorldData)
    MergeFrom(*source);
  }
}

void WorldData::MergeFrom(const WorldData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.WorldData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  obstaclecoords_.MergeFrom(from.obstaclecoords_);
  if (from.has_robotdata()) {
    mutable_robotdata()->::protocol::RobotData::MergeFrom(from.robotdata());
  }
  if (from.has_ballcoord()) {
    mutable_ballcoord()->::protocol::Coord::MergeFrom(from.ballcoord());
  }
}

void WorldData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.WorldData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorldData::CopyFrom(const WorldData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.WorldData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorldData::IsInitialized() const {
  return true;
}

void WorldData::Swap(WorldData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WorldData::InternalSwap(WorldData* other) {
  using std::swap;
  CastToBase(&obstaclecoords_)->InternalSwap(CastToBase(&other->obstaclecoords_));
  swap(robotdata_, other->robotdata_);
  swap(ballcoord_, other->ballcoord_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WorldData::GetMetadata() const {
  protobuf_world_5fdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_world_5fdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protocol::Coord* Arena::CreateMaybeMessage< ::protocol::Coord >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::Coord >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protocol::Position* Arena::CreateMaybeMessage< ::protocol::Position >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::Position >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protocol::WheelsVelocity* Arena::CreateMaybeMessage< ::protocol::WheelsVelocity >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::WheelsVelocity >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protocol::RobotData* Arena::CreateMaybeMessage< ::protocol::RobotData >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::RobotData >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protocol::WorldData* Arena::CreateMaybeMessage< ::protocol::WorldData >(Arena* arena) {
  return Arena::CreateInternal< ::protocol::WorldData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
