// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "world_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {

namespace {

const ::google::protobuf::Descriptor* Coord_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Coord_reflection_ = NULL;
const ::google::protobuf::Descriptor* Position_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Position_reflection_ = NULL;
const ::google::protobuf::Descriptor* WheelsVelocity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WheelsVelocity_reflection_ = NULL;
const ::google::protobuf::Descriptor* RobotData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotData_reflection_ = NULL;
const ::google::protobuf::Descriptor* WorldData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WorldData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_world_5fdata_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_world_5fdata_2eproto() {
  protobuf_AddDesc_world_5fdata_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "world_data.proto");
  GOOGLE_CHECK(file != NULL);
  Coord_descriptor_ = file->message_type(0);
  static const int Coord_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Coord, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Coord, y_),
  };
  Coord_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Coord_descriptor_,
      Coord::default_instance_,
      Coord_offsets_,
      -1,
      -1,
      -1,
      sizeof(Coord),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Coord, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Coord, _is_default_instance_));
  Position_descriptor_ = file->message_type(1);
  static const int Position_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, coord_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, theta_),
  };
  Position_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Position_descriptor_,
      Position::default_instance_,
      Position_offsets_,
      -1,
      -1,
      -1,
      sizeof(Position),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Position, _is_default_instance_));
  WheelsVelocity_descriptor_ = file->message_type(2);
  static const int WheelsVelocity_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WheelsVelocity, leftwheelvelocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WheelsVelocity, rightwheelvelocity_),
  };
  WheelsVelocity_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      WheelsVelocity_descriptor_,
      WheelsVelocity::default_instance_,
      WheelsVelocity_offsets_,
      -1,
      -1,
      -1,
      sizeof(WheelsVelocity),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WheelsVelocity, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WheelsVelocity, _is_default_instance_));
  RobotData_descriptor_ = file->message_type(3);
  static const int RobotData_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotData, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotData, wheelsvelocity_),
  };
  RobotData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RobotData_descriptor_,
      RobotData::default_instance_,
      RobotData_offsets_,
      -1,
      -1,
      -1,
      sizeof(RobotData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotData, _is_default_instance_));
  WorldData_descriptor_ = file->message_type(4);
  static const int WorldData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldData, robotdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldData, obstaclecoords_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldData, ballcoord_),
  };
  WorldData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      WorldData_descriptor_,
      WorldData::default_instance_,
      WorldData_offsets_,
      -1,
      -1,
      -1,
      sizeof(WorldData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WorldData, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_world_5fdata_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Coord_descriptor_, &Coord::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Position_descriptor_, &Position::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      WheelsVelocity_descriptor_, &WheelsVelocity::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RobotData_descriptor_, &RobotData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      WorldData_descriptor_, &WorldData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_world_5fdata_2eproto() {
  delete Coord::default_instance_;
  delete Coord_reflection_;
  delete Position::default_instance_;
  delete Position_reflection_;
  delete WheelsVelocity::default_instance_;
  delete WheelsVelocity_reflection_;
  delete RobotData::default_instance_;
  delete RobotData_reflection_;
  delete WorldData::default_instance_;
  delete WorldData_reflection_;
}

void protobuf_AddDesc_world_5fdata_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_world_5fdata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020world_data.proto\022\010protocol\"\035\n\005Coord\022\t\n"
    "\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"9\n\010Position\022\036\n\005coord"
    "\030\001 \001(\0132\017.protocol.Coord\022\r\n\005theta\030\002 \001(\001\"G"
    "\n\016WheelsVelocity\022\031\n\021leftWheelVelocity\030\001 "
    "\001(\001\022\032\n\022rightWheelVelocity\030\002 \001(\001\"c\n\tRobot"
    "Data\022$\n\010position\030\001 \001(\0132\022.protocol.Positi"
    "on\0220\n\016wheelsVelocity\030\002 \001(\0132\030.protocol.Wh"
    "eelsVelocity\"\200\001\n\tWorldData\022&\n\trobotData\030"
    "\001 \001(\0132\023.protocol.RobotData\022\'\n\016obstacleCo"
    "ords\030\002 \003(\0132\017.protocol.Coord\022\"\n\tballCoord"
    "\030\003 \001(\0132\017.protocol.Coordb\006proto3", 431);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "world_data.proto", &protobuf_RegisterTypes);
  Coord::default_instance_ = new Coord();
  Position::default_instance_ = new Position();
  WheelsVelocity::default_instance_ = new WheelsVelocity();
  RobotData::default_instance_ = new RobotData();
  WorldData::default_instance_ = new WorldData();
  Coord::default_instance_->InitAsDefaultInstance();
  Position::default_instance_->InitAsDefaultInstance();
  WheelsVelocity::default_instance_->InitAsDefaultInstance();
  RobotData::default_instance_->InitAsDefaultInstance();
  WorldData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_world_5fdata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_world_5fdata_2eproto {
  StaticDescriptorInitializer_world_5fdata_2eproto() {
    protobuf_AddDesc_world_5fdata_2eproto();
  }
} static_descriptor_initializer_world_5fdata_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Coord::kXFieldNumber;
const int Coord::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Coord::Coord()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.Coord)
}

void Coord::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Coord::Coord(const Coord& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.Coord)
}

void Coord::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
}

Coord::~Coord() {
  // @@protoc_insertion_point(destructor:protocol.Coord)
  SharedDtor();
}

void Coord::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Coord::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Coord::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Coord_descriptor_;
}

const Coord& Coord::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_world_5fdata_2eproto();
  return *default_instance_;
}

Coord* Coord::default_instance_ = NULL;

Coord* Coord::New(::google::protobuf::Arena* arena) const {
  Coord* n = new Coord;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Coord::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Coord)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Coord, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Coord*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, y_);

#undef ZR_HELPER_
#undef ZR_

}

bool Coord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.Coord)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_y;
        break;
      }

      // optional double y = 2;
      case 2: {
        if (tag == 17) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.Coord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.Coord)
  return false;
#undef DO_
}

void Coord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.Coord)
  // optional double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // optional double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // @@protoc_insertion_point(serialize_end:protocol.Coord)
}

::google::protobuf::uint8* Coord::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Coord)
  // optional double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // optional double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protocol.Coord)
  return target;
}

int Coord::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.Coord)
  int total_size = 0;

  // optional double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // optional double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Coord::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.Coord)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Coord* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Coord>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.Coord)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.Coord)
    MergeFrom(*source);
  }
}

void Coord::MergeFrom(const Coord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.Coord)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void Coord::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.Coord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Coord::CopyFrom(const Coord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Coord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Coord::IsInitialized() const {

  return true;
}

void Coord::Swap(Coord* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Coord::InternalSwap(Coord* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Coord::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Coord_descriptor_;
  metadata.reflection = Coord_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Coord

// optional double x = 1;
void Coord::clear_x() {
  x_ = 0;
}
 double Coord::x() const {
  // @@protoc_insertion_point(field_get:protocol.Coord.x)
  return x_;
}
 void Coord::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:protocol.Coord.x)
}

// optional double y = 2;
void Coord::clear_y() {
  y_ = 0;
}
 double Coord::y() const {
  // @@protoc_insertion_point(field_get:protocol.Coord.y)
  return y_;
}
 void Coord::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:protocol.Coord.y)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Position::kCoordFieldNumber;
const int Position::kThetaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Position::Position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.Position)
}

void Position::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  coord_ = const_cast< ::protocol::Coord*>(&::protocol::Coord::default_instance());
}

Position::Position(const Position& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.Position)
}

void Position::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  coord_ = NULL;
  theta_ = 0;
}

Position::~Position() {
  // @@protoc_insertion_point(destructor:protocol.Position)
  SharedDtor();
}

void Position::SharedDtor() {
  if (this != default_instance_) {
    delete coord_;
  }
}

void Position::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Position::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Position_descriptor_;
}

const Position& Position::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_world_5fdata_2eproto();
  return *default_instance_;
}

Position* Position::default_instance_ = NULL;

Position* Position::New(::google::protobuf::Arena* arena) const {
  Position* n = new Position;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.Position)
  if (GetArenaNoVirtual() == NULL && coord_ != NULL) delete coord_;
  coord_ = NULL;
  theta_ = 0;
}

bool Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.Position)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.Coord coord = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_coord()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_theta;
        break;
      }

      // optional double theta = 2;
      case 2: {
        if (tag == 17) {
         parse_theta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &theta_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.Position)
  return false;
#undef DO_
}

void Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.Position)
  // optional .protocol.Coord coord = 1;
  if (this->has_coord()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->coord_, output);
  }

  // optional double theta = 2;
  if (this->theta() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->theta(), output);
  }

  // @@protoc_insertion_point(serialize_end:protocol.Position)
}

::google::protobuf::uint8* Position::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.Position)
  // optional .protocol.Coord coord = 1;
  if (this->has_coord()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->coord_, false, target);
  }

  // optional double theta = 2;
  if (this->theta() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->theta(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protocol.Position)
  return target;
}

int Position::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.Position)
  int total_size = 0;

  // optional .protocol.Coord coord = 1;
  if (this->has_coord()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->coord_);
  }

  // optional double theta = 2;
  if (this->theta() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Position::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.Position)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Position* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Position>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.Position)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.Position)
    MergeFrom(*source);
  }
}

void Position::MergeFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.Position)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_coord()) {
    mutable_coord()->::protocol::Coord::MergeFrom(from.coord());
  }
  if (from.theta() != 0) {
    set_theta(from.theta());
  }
}

void Position::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Position::CopyFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Position::IsInitialized() const {

  return true;
}

void Position::Swap(Position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Position::InternalSwap(Position* other) {
  std::swap(coord_, other->coord_);
  std::swap(theta_, other->theta_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Position::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Position_descriptor_;
  metadata.reflection = Position_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Position

// optional .protocol.Coord coord = 1;
bool Position::has_coord() const {
  return !_is_default_instance_ && coord_ != NULL;
}
void Position::clear_coord() {
  if (GetArenaNoVirtual() == NULL && coord_ != NULL) delete coord_;
  coord_ = NULL;
}
const ::protocol::Coord& Position::coord() const {
  // @@protoc_insertion_point(field_get:protocol.Position.coord)
  return coord_ != NULL ? *coord_ : *default_instance_->coord_;
}
::protocol::Coord* Position::mutable_coord() {
  
  if (coord_ == NULL) {
    coord_ = new ::protocol::Coord;
  }
  // @@protoc_insertion_point(field_mutable:protocol.Position.coord)
  return coord_;
}
::protocol::Coord* Position::release_coord() {
  // @@protoc_insertion_point(field_release:protocol.Position.coord)
  
  ::protocol::Coord* temp = coord_;
  coord_ = NULL;
  return temp;
}
void Position::set_allocated_coord(::protocol::Coord* coord) {
  delete coord_;
  coord_ = coord;
  if (coord) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.Position.coord)
}

// optional double theta = 2;
void Position::clear_theta() {
  theta_ = 0;
}
 double Position::theta() const {
  // @@protoc_insertion_point(field_get:protocol.Position.theta)
  return theta_;
}
 void Position::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:protocol.Position.theta)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WheelsVelocity::kLeftWheelVelocityFieldNumber;
const int WheelsVelocity::kRightWheelVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WheelsVelocity::WheelsVelocity()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.WheelsVelocity)
}

void WheelsVelocity::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

WheelsVelocity::WheelsVelocity(const WheelsVelocity& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.WheelsVelocity)
}

void WheelsVelocity::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  leftwheelvelocity_ = 0;
  rightwheelvelocity_ = 0;
}

WheelsVelocity::~WheelsVelocity() {
  // @@protoc_insertion_point(destructor:protocol.WheelsVelocity)
  SharedDtor();
}

void WheelsVelocity::SharedDtor() {
  if (this != default_instance_) {
  }
}

void WheelsVelocity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WheelsVelocity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WheelsVelocity_descriptor_;
}

const WheelsVelocity& WheelsVelocity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_world_5fdata_2eproto();
  return *default_instance_;
}

WheelsVelocity* WheelsVelocity::default_instance_ = NULL;

WheelsVelocity* WheelsVelocity::New(::google::protobuf::Arena* arena) const {
  WheelsVelocity* n = new WheelsVelocity;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WheelsVelocity::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.WheelsVelocity)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(WheelsVelocity, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<WheelsVelocity*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(leftwheelvelocity_, rightwheelvelocity_);

#undef ZR_HELPER_
#undef ZR_

}

bool WheelsVelocity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.WheelsVelocity)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double leftWheelVelocity = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &leftwheelvelocity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_rightWheelVelocity;
        break;
      }

      // optional double rightWheelVelocity = 2;
      case 2: {
        if (tag == 17) {
         parse_rightWheelVelocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rightwheelvelocity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.WheelsVelocity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.WheelsVelocity)
  return false;
#undef DO_
}

void WheelsVelocity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.WheelsVelocity)
  // optional double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->leftwheelvelocity(), output);
  }

  // optional double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->rightwheelvelocity(), output);
  }

  // @@protoc_insertion_point(serialize_end:protocol.WheelsVelocity)
}

::google::protobuf::uint8* WheelsVelocity::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.WheelsVelocity)
  // optional double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->leftwheelvelocity(), target);
  }

  // optional double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->rightwheelvelocity(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protocol.WheelsVelocity)
  return target;
}

int WheelsVelocity::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.WheelsVelocity)
  int total_size = 0;

  // optional double leftWheelVelocity = 1;
  if (this->leftwheelvelocity() != 0) {
    total_size += 1 + 8;
  }

  // optional double rightWheelVelocity = 2;
  if (this->rightwheelvelocity() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WheelsVelocity::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.WheelsVelocity)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const WheelsVelocity* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const WheelsVelocity>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.WheelsVelocity)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.WheelsVelocity)
    MergeFrom(*source);
  }
}

void WheelsVelocity::MergeFrom(const WheelsVelocity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.WheelsVelocity)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.leftwheelvelocity() != 0) {
    set_leftwheelvelocity(from.leftwheelvelocity());
  }
  if (from.rightwheelvelocity() != 0) {
    set_rightwheelvelocity(from.rightwheelvelocity());
  }
}

void WheelsVelocity::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.WheelsVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WheelsVelocity::CopyFrom(const WheelsVelocity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.WheelsVelocity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WheelsVelocity::IsInitialized() const {

  return true;
}

void WheelsVelocity::Swap(WheelsVelocity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WheelsVelocity::InternalSwap(WheelsVelocity* other) {
  std::swap(leftwheelvelocity_, other->leftwheelvelocity_);
  std::swap(rightwheelvelocity_, other->rightwheelvelocity_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WheelsVelocity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WheelsVelocity_descriptor_;
  metadata.reflection = WheelsVelocity_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// WheelsVelocity

// optional double leftWheelVelocity = 1;
void WheelsVelocity::clear_leftwheelvelocity() {
  leftwheelvelocity_ = 0;
}
 double WheelsVelocity::leftwheelvelocity() const {
  // @@protoc_insertion_point(field_get:protocol.WheelsVelocity.leftWheelVelocity)
  return leftwheelvelocity_;
}
 void WheelsVelocity::set_leftwheelvelocity(double value) {
  
  leftwheelvelocity_ = value;
  // @@protoc_insertion_point(field_set:protocol.WheelsVelocity.leftWheelVelocity)
}

// optional double rightWheelVelocity = 2;
void WheelsVelocity::clear_rightwheelvelocity() {
  rightwheelvelocity_ = 0;
}
 double WheelsVelocity::rightwheelvelocity() const {
  // @@protoc_insertion_point(field_get:protocol.WheelsVelocity.rightWheelVelocity)
  return rightwheelvelocity_;
}
 void WheelsVelocity::set_rightwheelvelocity(double value) {
  
  rightwheelvelocity_ = value;
  // @@protoc_insertion_point(field_set:protocol.WheelsVelocity.rightWheelVelocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RobotData::kPositionFieldNumber;
const int RobotData::kWheelsVelocityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RobotData::RobotData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.RobotData)
}

void RobotData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  position_ = const_cast< ::protocol::Position*>(&::protocol::Position::default_instance());
  wheelsvelocity_ = const_cast< ::protocol::WheelsVelocity*>(&::protocol::WheelsVelocity::default_instance());
}

RobotData::RobotData(const RobotData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.RobotData)
}

void RobotData::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  position_ = NULL;
  wheelsvelocity_ = NULL;
}

RobotData::~RobotData() {
  // @@protoc_insertion_point(destructor:protocol.RobotData)
  SharedDtor();
}

void RobotData::SharedDtor() {
  if (this != default_instance_) {
    delete position_;
    delete wheelsvelocity_;
  }
}

void RobotData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RobotData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RobotData_descriptor_;
}

const RobotData& RobotData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_world_5fdata_2eproto();
  return *default_instance_;
}

RobotData* RobotData::default_instance_ = NULL;

RobotData* RobotData::New(::google::protobuf::Arena* arena) const {
  RobotData* n = new RobotData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RobotData::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.RobotData)
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
  if (GetArenaNoVirtual() == NULL && wheelsvelocity_ != NULL) delete wheelsvelocity_;
  wheelsvelocity_ = NULL;
}

bool RobotData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.RobotData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.Position position = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_wheelsVelocity;
        break;
      }

      // optional .protocol.WheelsVelocity wheelsVelocity = 2;
      case 2: {
        if (tag == 18) {
         parse_wheelsVelocity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_wheelsvelocity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.RobotData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.RobotData)
  return false;
#undef DO_
}

void RobotData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.RobotData)
  // optional .protocol.Position position = 1;
  if (this->has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->position_, output);
  }

  // optional .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->wheelsvelocity_, output);
  }

  // @@protoc_insertion_point(serialize_end:protocol.RobotData)
}

::google::protobuf::uint8* RobotData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.RobotData)
  // optional .protocol.Position position = 1;
  if (this->has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->position_, false, target);
  }

  // optional .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->wheelsvelocity_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protocol.RobotData)
  return target;
}

int RobotData::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.RobotData)
  int total_size = 0;

  // optional .protocol.Position position = 1;
  if (this->has_position()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->position_);
  }

  // optional .protocol.WheelsVelocity wheelsVelocity = 2;
  if (this->has_wheelsvelocity()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->wheelsvelocity_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RobotData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.RobotData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RobotData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RobotData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.RobotData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.RobotData)
    MergeFrom(*source);
  }
}

void RobotData::MergeFrom(const RobotData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.RobotData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_position()) {
    mutable_position()->::protocol::Position::MergeFrom(from.position());
  }
  if (from.has_wheelsvelocity()) {
    mutable_wheelsvelocity()->::protocol::WheelsVelocity::MergeFrom(from.wheelsvelocity());
  }
}

void RobotData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.RobotData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RobotData::CopyFrom(const RobotData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.RobotData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RobotData::IsInitialized() const {

  return true;
}

void RobotData::Swap(RobotData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RobotData::InternalSwap(RobotData* other) {
  std::swap(position_, other->position_);
  std::swap(wheelsvelocity_, other->wheelsvelocity_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RobotData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RobotData_descriptor_;
  metadata.reflection = RobotData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RobotData

// optional .protocol.Position position = 1;
bool RobotData::has_position() const {
  return !_is_default_instance_ && position_ != NULL;
}
void RobotData::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
}
const ::protocol::Position& RobotData::position() const {
  // @@protoc_insertion_point(field_get:protocol.RobotData.position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
::protocol::Position* RobotData::mutable_position() {
  
  if (position_ == NULL) {
    position_ = new ::protocol::Position;
  }
  // @@protoc_insertion_point(field_mutable:protocol.RobotData.position)
  return position_;
}
::protocol::Position* RobotData::release_position() {
  // @@protoc_insertion_point(field_release:protocol.RobotData.position)
  
  ::protocol::Position* temp = position_;
  position_ = NULL;
  return temp;
}
void RobotData::set_allocated_position(::protocol::Position* position) {
  delete position_;
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.RobotData.position)
}

// optional .protocol.WheelsVelocity wheelsVelocity = 2;
bool RobotData::has_wheelsvelocity() const {
  return !_is_default_instance_ && wheelsvelocity_ != NULL;
}
void RobotData::clear_wheelsvelocity() {
  if (GetArenaNoVirtual() == NULL && wheelsvelocity_ != NULL) delete wheelsvelocity_;
  wheelsvelocity_ = NULL;
}
const ::protocol::WheelsVelocity& RobotData::wheelsvelocity() const {
  // @@protoc_insertion_point(field_get:protocol.RobotData.wheelsVelocity)
  return wheelsvelocity_ != NULL ? *wheelsvelocity_ : *default_instance_->wheelsvelocity_;
}
::protocol::WheelsVelocity* RobotData::mutable_wheelsvelocity() {
  
  if (wheelsvelocity_ == NULL) {
    wheelsvelocity_ = new ::protocol::WheelsVelocity;
  }
  // @@protoc_insertion_point(field_mutable:protocol.RobotData.wheelsVelocity)
  return wheelsvelocity_;
}
::protocol::WheelsVelocity* RobotData::release_wheelsvelocity() {
  // @@protoc_insertion_point(field_release:protocol.RobotData.wheelsVelocity)
  
  ::protocol::WheelsVelocity* temp = wheelsvelocity_;
  wheelsvelocity_ = NULL;
  return temp;
}
void RobotData::set_allocated_wheelsvelocity(::protocol::WheelsVelocity* wheelsvelocity) {
  delete wheelsvelocity_;
  wheelsvelocity_ = wheelsvelocity;
  if (wheelsvelocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.RobotData.wheelsVelocity)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WorldData::kRobotDataFieldNumber;
const int WorldData::kObstacleCoordsFieldNumber;
const int WorldData::kBallCoordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WorldData::WorldData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.WorldData)
}

void WorldData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  robotdata_ = const_cast< ::protocol::RobotData*>(&::protocol::RobotData::default_instance());
  ballcoord_ = const_cast< ::protocol::Coord*>(&::protocol::Coord::default_instance());
}

WorldData::WorldData(const WorldData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.WorldData)
}

void WorldData::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  robotdata_ = NULL;
  ballcoord_ = NULL;
}

WorldData::~WorldData() {
  // @@protoc_insertion_point(destructor:protocol.WorldData)
  SharedDtor();
}

void WorldData::SharedDtor() {
  if (this != default_instance_) {
    delete robotdata_;
    delete ballcoord_;
  }
}

void WorldData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WorldData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WorldData_descriptor_;
}

const WorldData& WorldData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_world_5fdata_2eproto();
  return *default_instance_;
}

WorldData* WorldData::default_instance_ = NULL;

WorldData* WorldData::New(::google::protobuf::Arena* arena) const {
  WorldData* n = new WorldData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WorldData::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.WorldData)
  if (GetArenaNoVirtual() == NULL && robotdata_ != NULL) delete robotdata_;
  robotdata_ = NULL;
  if (GetArenaNoVirtual() == NULL && ballcoord_ != NULL) delete ballcoord_;
  ballcoord_ = NULL;
  obstaclecoords_.Clear();
}

bool WorldData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.WorldData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .protocol.RobotData robotData = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_robotdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_obstacleCoords;
        break;
      }

      // repeated .protocol.Coord obstacleCoords = 2;
      case 2: {
        if (tag == 18) {
         parse_obstacleCoords:
          DO_(input->IncrementRecursionDepth());
         parse_loop_obstacleCoords:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_obstaclecoords()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_obstacleCoords;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(26)) goto parse_ballCoord;
        break;
      }

      // optional .protocol.Coord ballCoord = 3;
      case 3: {
        if (tag == 26) {
         parse_ballCoord:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ballcoord()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.WorldData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.WorldData)
  return false;
#undef DO_
}

void WorldData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.WorldData)
  // optional .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->robotdata_, output);
  }

  // repeated .protocol.Coord obstacleCoords = 2;
  for (unsigned int i = 0, n = this->obstaclecoords_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->obstaclecoords(i), output);
  }

  // optional .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->ballcoord_, output);
  }

  // @@protoc_insertion_point(serialize_end:protocol.WorldData)
}

::google::protobuf::uint8* WorldData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.WorldData)
  // optional .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->robotdata_, false, target);
  }

  // repeated .protocol.Coord obstacleCoords = 2;
  for (unsigned int i = 0, n = this->obstaclecoords_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->obstaclecoords(i), false, target);
  }

  // optional .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->ballcoord_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:protocol.WorldData)
  return target;
}

int WorldData::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.WorldData)
  int total_size = 0;

  // optional .protocol.RobotData robotData = 1;
  if (this->has_robotdata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->robotdata_);
  }

  // optional .protocol.Coord ballCoord = 3;
  if (this->has_ballcoord()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->ballcoord_);
  }

  // repeated .protocol.Coord obstacleCoords = 2;
  total_size += 1 * this->obstaclecoords_size();
  for (int i = 0; i < this->obstaclecoords_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->obstaclecoords(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WorldData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.WorldData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const WorldData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const WorldData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.WorldData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.WorldData)
    MergeFrom(*source);
  }
}

void WorldData::MergeFrom(const WorldData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.WorldData)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  obstaclecoords_.MergeFrom(from.obstaclecoords_);
  if (from.has_robotdata()) {
    mutable_robotdata()->::protocol::RobotData::MergeFrom(from.robotdata());
  }
  if (from.has_ballcoord()) {
    mutable_ballcoord()->::protocol::Coord::MergeFrom(from.ballcoord());
  }
}

void WorldData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.WorldData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WorldData::CopyFrom(const WorldData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.WorldData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WorldData::IsInitialized() const {

  return true;
}

void WorldData::Swap(WorldData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WorldData::InternalSwap(WorldData* other) {
  std::swap(robotdata_, other->robotdata_);
  obstaclecoords_.UnsafeArenaSwap(&other->obstaclecoords_);
  std::swap(ballcoord_, other->ballcoord_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WorldData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WorldData_descriptor_;
  metadata.reflection = WorldData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// WorldData

// optional .protocol.RobotData robotData = 1;
bool WorldData::has_robotdata() const {
  return !_is_default_instance_ && robotdata_ != NULL;
}
void WorldData::clear_robotdata() {
  if (GetArenaNoVirtual() == NULL && robotdata_ != NULL) delete robotdata_;
  robotdata_ = NULL;
}
const ::protocol::RobotData& WorldData::robotdata() const {
  // @@protoc_insertion_point(field_get:protocol.WorldData.robotData)
  return robotdata_ != NULL ? *robotdata_ : *default_instance_->robotdata_;
}
::protocol::RobotData* WorldData::mutable_robotdata() {
  
  if (robotdata_ == NULL) {
    robotdata_ = new ::protocol::RobotData;
  }
  // @@protoc_insertion_point(field_mutable:protocol.WorldData.robotData)
  return robotdata_;
}
::protocol::RobotData* WorldData::release_robotdata() {
  // @@protoc_insertion_point(field_release:protocol.WorldData.robotData)
  
  ::protocol::RobotData* temp = robotdata_;
  robotdata_ = NULL;
  return temp;
}
void WorldData::set_allocated_robotdata(::protocol::RobotData* robotdata) {
  delete robotdata_;
  robotdata_ = robotdata;
  if (robotdata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.WorldData.robotData)
}

// repeated .protocol.Coord obstacleCoords = 2;
int WorldData::obstaclecoords_size() const {
  return obstaclecoords_.size();
}
void WorldData::clear_obstaclecoords() {
  obstaclecoords_.Clear();
}
const ::protocol::Coord& WorldData::obstaclecoords(int index) const {
  // @@protoc_insertion_point(field_get:protocol.WorldData.obstacleCoords)
  return obstaclecoords_.Get(index);
}
::protocol::Coord* WorldData::mutable_obstaclecoords(int index) {
  // @@protoc_insertion_point(field_mutable:protocol.WorldData.obstacleCoords)
  return obstaclecoords_.Mutable(index);
}
::protocol::Coord* WorldData::add_obstaclecoords() {
  // @@protoc_insertion_point(field_add:protocol.WorldData.obstacleCoords)
  return obstaclecoords_.Add();
}
::google::protobuf::RepeatedPtrField< ::protocol::Coord >*
WorldData::mutable_obstaclecoords() {
  // @@protoc_insertion_point(field_mutable_list:protocol.WorldData.obstacleCoords)
  return &obstaclecoords_;
}
const ::google::protobuf::RepeatedPtrField< ::protocol::Coord >&
WorldData::obstaclecoords() const {
  // @@protoc_insertion_point(field_list:protocol.WorldData.obstacleCoords)
  return obstaclecoords_;
}

// optional .protocol.Coord ballCoord = 3;
bool WorldData::has_ballcoord() const {
  return !_is_default_instance_ && ballcoord_ != NULL;
}
void WorldData::clear_ballcoord() {
  if (GetArenaNoVirtual() == NULL && ballcoord_ != NULL) delete ballcoord_;
  ballcoord_ = NULL;
}
const ::protocol::Coord& WorldData::ballcoord() const {
  // @@protoc_insertion_point(field_get:protocol.WorldData.ballCoord)
  return ballcoord_ != NULL ? *ballcoord_ : *default_instance_->ballcoord_;
}
::protocol::Coord* WorldData::mutable_ballcoord() {
  
  if (ballcoord_ == NULL) {
    ballcoord_ = new ::protocol::Coord;
  }
  // @@protoc_insertion_point(field_mutable:protocol.WorldData.ballCoord)
  return ballcoord_;
}
::protocol::Coord* WorldData::release_ballcoord() {
  // @@protoc_insertion_point(field_release:protocol.WorldData.ballCoord)
  
  ::protocol::Coord* temp = ballcoord_;
  ballcoord_ = NULL;
  return temp;
}
void WorldData::set_allocated_ballcoord(::protocol::Coord* ballcoord) {
  delete ballcoord_;
  ballcoord_ = ballcoord;
  if (ballcoord) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.WorldData.ballCoord)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)
